// reasoning.go — interleaved-thinking capture & replay.
//
// OpenRouter exposes a model's thinking on the assistant message as `reasoning`
// (plaintext) and `reasoning_details` (an ordered array of typed blocks:
// reasoning.text / reasoning.summary / reasoning.encrypted, each with
// id/format/index and a type-specific payload). Per the OpenRouter docs, when
// passing reasoning back "the entire sequence of consecutive reasoning blocks
// must match the outputs generated by the model during the original request;
// you cannot rearrange or modify the sequence".
//
// Replay policy (per-model, mirroring the lab guidance the same way the
// orchestrator's adaptiveForModel keys sampling/prompts by slug):
//   - MiniMax ("minimax/…"): the lab MANDATES replaying prior-turn thinking
//     verbatim — dropping it costs 2–40% on agentic benches (SWE-bench
//     69.4→67.2, Tau² −35.9%). REPLAY.
//   - Qwen: the lab explicitly says prior-turn thinking must NOT be replayed
//     (history should hold only final output). STRIP.
//   - Everyone else: the field is at best ignored and at worst a 400. STRIP.
//
// Kill-switch: OPEN_AGENT_NO_REASONING_REPLAY=1 disables both capture and
// replay, so a provider-side format change can be neutralized in the field
// without a release (same convention as OPEN_AGENT_ADAPTIVE=0 for the
// adaptive prompt layer, but its own switch — this is a wire-correctness
// feature, not a prompt tweak).
package llm

import (
	"encoding/json"
	"os"
	"strings"
)

// reasoningReplayDisabled is the runtime kill-switch check (read per call so
// tests can flip it with t.Setenv and long-lived daemons honor a restart-free
// env change from a wrapper script).
func reasoningReplayDisabled() bool {
	return os.Getenv("OPEN_AGENT_NO_REASONING_REPLAY") == "1"
}

// replayReasoningFor reports whether captured assistant reasoning should be
// sent back to this model in the request history.
func replayReasoningFor(model string) bool {
	return !reasoningReplayDisabled() && strings.HasPrefix(model, "minimax/")
}

// stripReasoning returns msgs with the reasoning fields zeroed, copying only
// when something must actually be stripped. The caller's slice is NEVER
// mutated: history keeps the captured thinking so it is still there when a
// replay-mandating model is called with the same history later.
func stripReasoning(msgs []Message) []Message {
	dirty := false
	for i := range msgs {
		if msgs[i].Reasoning != "" || len(msgs[i].ReasoningDetails) > 0 {
			dirty = true
			break
		}
	}
	if !dirty {
		return msgs
	}
	cp := make([]Message, len(msgs))
	copy(cp, msgs)
	for i := range cp {
		cp[i].Reasoning = ""
		cp[i].ReasoningDetails = nil
	}
	return cp
}

// reasoningAcc accumulates streaming reasoning deltas into the canonical
// non-streaming shape. `reasoning` text deltas concatenate; each
// `reasoning_details` delta element either continues an existing block (same
// `index`, like tool_calls deltas) or starts a new one, preserving arrival
// order. Blocks are kept as generic maps so provider fields we don't model
// (signature, future additions) survive the round trip; only the streaming
// path re-marshals — the non-streaming path stays byte-verbatim.
type reasoningAcc struct {
	text   strings.Builder
	blocks []map[string]any
	byIdx  map[int]map[string]any
}

func (ra *reasoningAcc) addText(s string) { ra.text.WriteString(s) }

func (ra *reasoningAcc) add(raw json.RawMessage) {
	var m map[string]any
	if json.Unmarshal(raw, &m) != nil || len(m) == 0 {
		return
	}
	if idx, ok := blockIndex(m); ok {
		if ra.byIdx == nil {
			ra.byIdx = map[int]map[string]any{}
		}
		if tgt, seen := ra.byIdx[idx]; seen {
			mergeReasoningBlock(tgt, m)
			return
		}
		ra.byIdx[idx] = m
		ra.blocks = append(ra.blocks, m)
		return
	}
	// No index: treat as a continuation of the previous block when the type/id
	// agree, otherwise as a new standalone block.
	if n := len(ra.blocks); n > 0 && sameReasoningBlock(ra.blocks[n-1], m) {
		mergeReasoningBlock(ra.blocks[n-1], m)
		return
	}
	ra.blocks = append(ra.blocks, m)
}

// apply writes the accumulated reasoning onto the assembled assistant message.
func (ra *reasoningAcc) apply(msg *Message) {
	if ra.text.Len() > 0 {
		msg.Reasoning = ra.text.String()
	}
	if len(ra.blocks) > 0 {
		if b, err := json.Marshal(ra.blocks); err == nil {
			msg.ReasoningDetails = b
		}
	}
}

func blockIndex(m map[string]any) (int, bool) {
	f, ok := m["index"].(float64)
	if !ok {
		return 0, false
	}
	return int(f), true
}

// sameReasoningBlock reports whether b is a CONTINUATION of a (only consulted
// on the no-index fallback path). A pure payload delta (no type) continues the
// previous block; a delta that declares a type is a new logical block unless it
// also carries the SAME non-empty id — merging two distinct same-type blocks
// that merely lack ids would fabricate a sequence the provider never produced
// (and "the sequence must match the original request").
func sameReasoningBlock(a, b map[string]any) bool {
	bt, _ := b["type"].(string)
	if bt == "" {
		return true // pure continuation payload ({"text": "…"})
	}
	at, _ := a["type"].(string)
	if bt != at {
		return false
	}
	aid, _ := a["id"].(string)
	bid, _ := b["id"].(string)
	return aid != "" && aid == bid
}

// mergeReasoningBlock folds a continuation delta into an accumulated block:
// payload strings (text/summary/data) concatenate in order, everything else
// (id, format, signature, …) is filled in when the delta carries a value.
func mergeReasoningBlock(tgt, delta map[string]any) {
	for k, v := range delta {
		switch k {
		case "text", "summary", "data":
			s, isStr := v.(string)
			if !isStr {
				continue // never fabricate an empty payload key from null/non-string
			}
			prev, _ := tgt[k].(string)
			tgt[k] = prev + s
		case "index":
			// keep the first-seen index
			if _, ok := tgt[k]; !ok {
				tgt[k] = v
			}
		default:
			if s, isStr := v.(string); isStr && s == "" {
				continue // don't clobber with an empty string
			}
			if v == nil {
				continue // don't clobber with null
			}
			tgt[k] = v
		}
	}
}
